CREATE TABLE IF NOT EXISTS categories ( --Категории
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) UNIQUE NOT NULL,
  CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users ( --Категории
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) UNIQUE NOT NULL,
  email VARCHAR(64) UNIQUE NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events ( --Мероприятия
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT REFERENCES categories NOT NULL,
  description VARCHAR(7000) NOT NULL,--VARCHAR(7000) NOT NULL TEXT
  event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  location_lat FLOAT NOT NULL,
  location_lon FLOAT NOT NULL,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  participant_limit INTEGER NOT NULL DEFAULT 0,
  request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
  title VARCHAR(120) NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  published_on TIMESTAMP WITHOUT TIME ZONE,
  state VARCHAR(10) NOT NULL,
  CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT fk_init_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS event_applications ( --Заявки участников
  id SERIAL PRIMARY KEY,
  event_id INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  applicant_name VARCHAR(255),
  applicant_email VARCHAR(255),
  applicant_phone VARCHAR(50),
  additional_info TEXT,
  status VARCHAR(50), -- например, 'pending', 'approved', 'rejected'
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_selection_settings ( --Настройки отбора
  id SERIAL PRIMARY KEY,
  event_id INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  selection_criteria TEXT,
  max_participants INT,
  rules TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_pickups ( --Подборки мероприятий
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  description TEXT,
  event_ids INTEGER[], -- Можно использовать массив ID, или создать отдельную таблицу для связи many-to-many
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

