CREATE TABLE IF NOT EXISTS categories ( --Категории
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) UNIQUE NOT NULL,
  CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users ( --Категории
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) UNIQUE NOT NULL,
  email VARCHAR(64) UNIQUE NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events ( --Мероприятия
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT REFERENCES categories NOT NULL,
  description VARCHAR(7000) NOT NULL,--VARCHAR(7000) NOT NULL TEXT
  event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  location_lat FLOAT NOT NULL,
  location_lon FLOAT NOT NULL,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  participant_limit INTEGER NOT NULL DEFAULT 0,
  request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
  title VARCHAR(120) NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  published_on TIMESTAMP WITHOUT TIME ZONE,
  state VARCHAR(10) NOT NULL,
  CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT fk_init_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS participation_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event BIGINT NOT NULL,
    requester BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_participation_request PRIMARY KEY (id)
);

-- Таблица для подборки
CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    pinned BOOLEAN DEFAULT false,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

-- Таблица для связи подборки и событий
CREATE TABLE IF NOT EXISTS compilation_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL, -- предполагается, что есть таблица с событиями
    CONSTRAINT pk_compilation_event PRIMARY KEY (id)
);
